### PR TITLE
Fix GetAudioEncoderConfigurations media ver20

### LINKED ISSUE #47: Fix/remove Onvif.Media.Ver20.GetAudioEncoderConfiguration from media ver20
Media ver20 doesn't have `GetAudioEncoderConfiguration` but it has `GetAudioEncoderConfigurations` which accepts `profile_token` and `configuration_token`

### PR DESCRIPTION
**Pull request by waranlogesh**
Fixes #47

### CODE REVIEW

File: lib/media/ver20/get_audio_encoder_configuration.ex [hunk 1]
```diff
@@ -1,36 +0,0 @@
-defmodule Onvif.Media.Ver20.GetAudioEncoderConfiguration do
```
Comment (hammeraj) [inline lib/media/ver20/get_audio_encoder_configuration.ex:1]: does this need to be deleted? or can we just fix the namespacing in the request?

Comment (waranlogesh) [reply lib/media/ver20/get_audio_encoder_configuration.ex:1]: Yes `GetAudioEncoderConfiguration` doesn't exit in media ver20 onvif spec. This was copy-paste error by me in f4071614b5f0555

Comment (waranlogesh) [reply lib/media/ver20/get_audio_encoder_configuration.ex:1]: Tested with uniview since axis doesn't support audio. But axis responded with correct response that audio not supported

**Review by hammeraj — APPROVED** [review]
